version: 2
jobs:
  build:
    working_directory: ~/garriegue_coq_lecture
    docker:
      - image: coqorg/coq
    steps:
      - checkout
      - run:
          name: compile .v
          command: |
            source ~/.profile
            ./configure.sh
            make

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
